// Auth Routes — STUB
// TODO (Person 1): Implement POST /auth/register and POST /auth/login.
// Signature expected by app.js:  module.exports = express.Router()

const express = require('express');

const router = express.Router();

const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');

const users = require('../data/users.json'); // In-memory "database" of users. Do not edit this file directly.
const SECRET_KEY = "hollanov";

//valudate email

function validateEmail(email) {
    const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return re.test(email);

}

// POST /auth/register
router.post('/register', async (req, res) => {
    const { username, email, password } = req.body;

    if (!username || !email || !password) {
        return res.status(400).json({ message: "All fields required" });
    }

    if (users.find(u => u.email === email)) {
        return res.status(400).json({ message: "Email already registered" });
    }

    const hashedPassword = await bcrypt.hash(password, 10);

    users.push({ username, email, password: hashedPassword });

    // ✅ Auto-login after register (important for your flow)
    const token = jwt.sign({ email, username }, SECRET_KEY, { expiresIn: '1h' });

    res.status(201).json({
        message: "User registered successfully",
        token
    });
});

//POST /auth/login
router.post('/login', async (req, res) => {
    const { email, password } = req.body;

    const user = users.find(u => u.email === email);

    if (!user) {
        return res.status(400).json({
            message: "No account found. Please register first."
        });
    }

    const valid = await bcrypt.compare(password, user.password);

    if (!valid) {
        return res.status(400).json({ message: "Invalid password" });
    }

    const token = jwt.sign(
        { email: user.email, username: user.username },
        SECRET_KEY,
        { expiresIn: '1h' }
    );

    res.json({ token });
});

module.exports = router;
